# API URL Prefix
URL_PREFIX_VERSION1 = '/api/v1'
APP_HOST = '0.0.0.0'
APP_PORT = 8000

# Boolean status code
STATUS_ZERO = 0
STATUS_ONE = 1
STATUS_TWO = 2
STATUS_FOUR = 4
STATUS_THREE = 3
STATUS_FIVE = 5
STATUS_SIX = 6
STATUS_SEVEN = 7
STATUS_EIGHT = 8
STATUS_NINE = 9
STATUS_TEN = 10
STATUS_TRUE = True
STATUS_FALSE = False
STATUS_NULL = None

# Entity status
STATUS_ACTIVE = 'active'
STATUS_INACTIVE = 'inactive'
STATUS_PUBLISHED = 'published'
STATUS_UNPUBLISHED = 'unpublished'
STATUS_CREATE = 'create'
STATUS_UPDATE = 'update'
STATUS_DELETE = 'delete'
STATUS_ALL = 'all'
STATUS_NEW = 'new'
STATUS_SUCCESS = 'success'
STATUS_ERROR = 'error'

PER_PAGE = 10
PAGE_NUMBER = 1
ORDER_OP = 'desc'
ORDER_COLUMN = 'id' # Id for the column id
PRODUCT_ORDER_COLUMN = "publish_sequence"